# Generated by Django 6.1.1 on 2026-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(default='A', max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('poisoned', models.BooleanField(default=False)),
                ('dnssec_status', models.CharField(choices=[('SECURE', 'Sécurisé'), ('INSECURE', 'Non sécurisé'), ('BOGUS', 'Erroné'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['domain_name', 'record_type'],
                'indexes': [models.Index(fields=['domain_name', 'record_type'], name='dnssec_simu_domain__e80de3_idx'), models.Index(fields=['poisoned'], name='dnssec_simu_poisone_f1c05a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DNSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(default='A', max_length=10)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_value', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('cache_hit', 'Cache Hit'), ('cache_miss', 'Cache Miss'), ('not_found', 'Not Found'), ('poisoned', 'Poisoned'), ('dnssec_secure', 'DNSSEC Secure'), ('dnssec_bogus', 'DNSSEC Bogus'), ('dnssec_insecure', 'DNSSEC Insecure')], default='cache_miss', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain_name', 'status'], name='dnssec_simu_domain__4f7818_idx')],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('TXT', 'TXT'), ('DNSKEY', 'DNSKEY'), ('RRSIG', 'RRSIG'), ('DS', 'DS'), ('NSEC', 'NSEC'), ('NSEC3', 'NSEC3')], default='A', max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('authoritative', models.BooleanField(default=True)),
                ('is_dnssec_signed', models.BooleanField(default=False)),
                ('algorithm', models.IntegerField(blank=True, null=True)),
                ('key_tag', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain_name', 'record_type', 'value'],
                'indexes': [models.Index(fields=['domain_name', 'record_type'], name='dnssec_simu_domain__e9ca12_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=255)),
                ('key_tag', models.IntegerField()),
                ('algorithm', models.IntegerField()),
                ('public_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'key_tag', 'algorithm')},
            },
        ),
    ]
