# Generated by Django 6.1 on 2026-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('poisoned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['domain_name', 'record_type'],
            },
        ),
        migrations.CreateModel(
            name='DNSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(default='A', max_length=10)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_value', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('cache_it', 'Cache Hit'), ('cache_miss', 'Cache Miss'), ('poisoned', 'Poisoned Response')], default='cache_miss', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('TXT', 'TXT')], default='A', max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('authoritative', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain_name', 'record_type'],
                'unique_together': {('domain_name', 'record_type')},
            },
        ),
    ]
