# Generated by Django 6.1 on 2026-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsquery',
            name='status',
            field=models.CharField(choices=[('cache_hit', 'Cache Hit'), ('cache_miss', 'Cache Miss'), ('poisoned', 'Poisoned Response')], default='cache_miss', max_length=30),
        ),
    ]
